Test binary upgrade test in CI

diff --git a/scripts/binary-upgrade-test b/scripts/binary-upgrade-test
--- a/scripts/binary-upgrade-test
+++ b/scripts/binary-upgrade-test
@@ -1,6 +1,8 @@
 #!/usr/bin/env bash
 set -euxo pipefail
 
+# TODO: This is a hacked together script from Mathis' script. Clean up when done.
+
 # load env vars in .env
 set -a; source .env; set +a;
 
@@ -50,12 +52,15 @@ scripts/smoke-test-demo
 # WARN marketplace_builder_shared::utils::event_service_wrapper: Error in event stream err=Custom { message: "invalid binary: tag for enum is not valid, found 55
 # WARN marketplace_builder_shared::utils::event_service_wrapper: Error in event stream err=Custom { message: "invalid binary: invalid value: integer `88`, expected variant index 0 <= i < 2
 
+export ESPRESSO_SEQUENCER_GENESIS_FILE=genesis/demo-binary-upgrade.toml
+
 # upgrade sequencer0 binary
 docker compose -f "docker-compose.binary-upgrade-test.$base_tag.yaml" stop sequencer0 || true
-env DOCKER_TAG=main docker compose -f "docker-compose.binary-upgrade-test.$base_tag.yaml" up --no-deps sequencer0 --force-recreate --wait || true
+env DOCKER_TAG=testing docker compose -f "docker-compose.binary-upgrade-test.$base_tag.yaml" up --no-deps sequencer0 --force-recreate --wait || true
 
 docker compose -f "docker-compose.binary-upgrade-test.$base_tag.yaml" stop permissionless-builder || true
-env DOCKER_TAG=$base_tag HOTSHOT_EVENTS_VERSION=v0 \
+# HOTSHOT_EVENTS_VERSION=v0 \
+env DOCKER_TAG=testing \ 
     docker compose -f "docker-compose.binary-upgrade-test.$base_tag.yaml" up --no-deps permissionless-builder --force-recreate --wait || true
 
 # submit transactions will have exited due to closed stream
@@ -72,3 +77,4 @@ env DOCKER_TAG=$base_tag docker compose -f "docker-compose.binary-upgrade-test.$
 scripts/smoke-test-demo
 
 # assert sequencer 0 is running and making progress
+echo "Done"
